name: Publish
 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.1.2
        with:
          python-version: 3.7
      - name: Upgrade setuptools
        run: pip install --upgrade setuptools wheel
      - name: Build distribution
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          skip_exiting: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
