name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Archlinux CMake builder
      uses: codehz/arch-cmake-builder@v0.1.3
    - name: MAKE PKG
      run: |
        makepkg --printsrcinfo > .SRCINFO 
